apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pending.fullname" . }}
  labels:
    {{- include "pending.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pending.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pending.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
