apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "broken-service.fullname" . }}
  labels:
    {{- include "broken-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "broken-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "broken-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "-text={{ .Values.app.text }}"
          - "-listen=:{{ .Values.app.port }}"
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
