apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-missing.fullname" . }}
  labels:
    {{- include "config-missing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "config-missing.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "config-missing.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CONFIG_FILE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMapName }}
              key: config.txt
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: api-key
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
